# Generated by Django 4.2.6 on 2023-11-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_date_scheduled_alter_post_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_edited',
        ),
    ]
