# Generated by Django 4.2.6 on 2023-12-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_is_negative_comment_is_profane_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedPost',
        ),
    ]
