# Generated by Django 4.2.6 on 2023-11-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscriber',
            name='is_subscribed',
        ),
    ]
