# Generated by Django 4.2.6 on 2023-12-02 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_emailsubscriber_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
